name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install linters
        run: sudo apt-get install -y eslint
      - name: Lint code
        run: eslint .

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build app
        run: |
          npm install
          npm run build
      - name: Build docker image
        run: |
          docker build -t nginx-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          curl -LO https://github.com/hashicorp/terraform/releases/download/v1.2.0/terraform_1.2.0_linux_amd64.zip
          unzip terraform_1.2.0_linux_amd64.zip
          cd terraform 

      - name: Terraform Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Run playbook
        run: |
          ansible-playbook -i inventory playbook.yml
          alert.yml

